# Generated by Django 2.1.5 on 2022-02-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pase',
            new_name='Page',
        ),
    ]
