# Generated by Django 2.1.5 on 2022-09-21 16:47

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="last_visit",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 9, 21, 16, 47, 47, 124969)
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
