# Generated by Django 2.1.5 on 2022-09-21 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20220921_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 16, 52, 27, 46844)),
        ),
    ]
