# Generated by Django 2.1.5 on 2023-03-13 18:53

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0005_auto_20230115_1408"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="rango.Category",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="last_visit",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 13, 21, 53, 40, 379419)
            ),
        ),
    ]
