# Generated by Django 2.1.5 on 2022-03-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20220317_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Title',
        ),
    ]
