# Generated by Django 2.1.5 on 2022-03-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20220324_1534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Page',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
